[16기 장준영] Add: profile_CRUD
wecode-bootcamp-korea/16-2nd-bestgo-backend pull request #10
Opened 2021-02-03 02:44 UTC by FreshTuna

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
프로필  엔드포인트 구현 
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.

2021-02-03 11:51 UTC, FreshTuna commented on users/views.py
> +        } for master in masters ]
master.review_set.first().content 가 쿼리를 너무 많이 발생시켜서 캐싱시키고 싶습니다..

2021-02-04 02:00 UTC, jamessoun93 requested changes

2021-02-04 02:00 UTC, jamessoun93 commented on users/views.py
> +        sort_method = request.GET.get('sorted_by') if request.GET.get('sorted_by') else 'id'
```suggestion
        sort_method = request.GET.get('sorted_by', 'id')
```
get() 메소드의 특성을 활용하여 'sorted_by' 를 못찾았을 시, default 로 'id'를 주실 수 있겠네요.

2021-02-04 02:00 UTC, jamessoun93 commented on users/views.py
> +                        .annotate(avg=Avg('review__rating')).order_by(sort_method)
```suggestion
        masters     = Master.objects.select_related('user')\
                                    .prefetch_related('review_set')\
                                    .annotate(avg=Avg('review__rating'))\
                                    .order_by(sort_method)
```

2021-02-04 02:00 UTC, jamessoun93 commented on users/views.py
> +                        .annotate(avg=Avg('review__rating')).order_by(sort_method)
이왕 `\` 활용하시는거 더 가독성 좋다고 생각하는 방향으로 정리해보았습니다 :)

2021-02-04 02:00 UTC, jamessoun93 commented on users/views.py
> +                prefetch_related('masterservice_set__service').get(id=master_id)
여기도 한번 수정해보세요~

2021-02-04 02:00 UTC, jamessoun93 commented on users/views.py
> +            }]
변수명으로 보아 dictionary 를 반환해주실 생각이신 것 같은데, 왜 list 에 감싸져 있을까요~?

2021-02-04 02:00 UTC, jamessoun93 commented on users/views.py
> +            master_services = master.masterservice_set.all()
해당 마스터가 제공하는 서비스가 많은 경우 select_related 를 적용해주시는게 좋을 것 같습니다!

2021-02-04 02:10 UTC, FreshTuna commented on users/views.py
> +        sort_method = request.GET.get('sorted_by') if request.GET.get('sorted_by') else 'id'
피드백 감사합니다!! get을 제대로 활용하지 못했었네요

2021-02-04 02:11 UTC, FreshTuna commented on users/views.py
> +                        .annotate(avg=Avg('review__rating')).order_by(sort_method)
수정했습니다! 좋은 방법인 것 같아요

2021-02-04 02:13 UTC, FreshTuna commented on users/views.py
> +            }]
아 이 부분은 저도 확실하게 이해하진 못했지만 프런트에서 이렇게 보내야 더 편하다고 해서 임시로 이렇게 바꿔 놓았습니다.

2021-02-04 07:52 UTC, jamessoun93 commented
LGTM

2021-02-04 07:52 UTC, merged