[16기 장준영]Add: users app views.py 작성
wecode-bootcamp-korea/16-2nd-bestgo-backend pull request #2
Opened 2021-01-27 08:07 UTC by FreshTuna

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 뷰, 회원가입 뷰 작성
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- users app signup, signin views.py 작성

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [ ] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.

2021-01-28 01:41 UTC, jamessoun93 reviewed
Unit Test 세션 후 올려주시면 추가로 확인하겠습니다.

2021-01-28 01:47 UTC, jamessoun93 requested changes

2021-01-28 01:47 UTC, jamessoun93 commented on users/views.py
> +from django.utils.html      import strip_tags
쓰이는 곳이 없는데 나중에 사용하실때 추가해주세요.

2021-01-28 01:48 UTC, FreshTuna commented on users/views.py
> +from django.utils.html      import strip_tags
아 넵! 추가 기능 구현하는데 필요한 것인데 빼먹고 안뺏네요.
피드백 감사합니다.

2021-01-28 01:51 UTC, jamessoun93 requested changes

2021-01-28 01:51 UTC, jamessoun93 commented on users/views.py
> +            if not (re.findall(r'[0-9]',password) and re.findall(r'[a-zA-Z]',password)):
password validation 로직도 util 함수로 분리해주시면 깔끔해질것 같네요!

2021-01-28 01:51 UTC, jamessoun93 commented on users/views.py
> +            return JsonResponse({'MESSAGE':'USER_CREATED'}, status=201)
구분을 위해 아래 빈 줄 추가해주세요.

2021-01-28 01:51 UTC, jamessoun93 commented on users/views.py
> +            return JsonResponse({'MESSAGE':'SUCCESS', 'TOKEN':user_token}, status=200)
여기도 위아래로 한줄씩 추가해주세요.

2021-01-28 08:49 UTC, soheon-lee commented on users/tests.py
> +        print(response.json())
테스트용 프린트 문은 제거해주세요

2021-01-28 08:49 UTC, soheon-lee commented on users/tests.py
> +        print(response.json())
파일 곳곳에 print문이 있어서 다 지워주세요 :)

2021-01-28 08:49 UTC, soheon-lee commented on users/tests.py
> +            'password':'1a2s3d4fa'
텍스트 관리하실때 쌍따옴표와 홑따옴표 통일해주세요 :)

2021-01-28 10:42 UTC, FreshTuna commented on users/tests.py
> +        print(response.json())
깜빡하고 안지웠네요! 감사합니다.

2021-01-28 10:42 UTC, FreshTuna commented on users/tests.py
> +            'password':'1a2s3d4fa'
넵! 수정했습니다.

2021-01-29 01:33 UTC, soheon-lee commented on users/views.py
> +            user= User.objects.get(email=email)
```suggestion
            user = User.objects.get(email=email)
```

2021-01-29 01:50 UTC, soheon-lee commented
LGTM!

2021-01-29 01:50 UTC, merged