[16기 장준영] Add: users socail_login  & password_reset
wecode-bootcamp-korea/16-2nd-bestgo-backend pull request #9
Opened 2021-02-01 16:00 UTC by FreshTuna

Add: social login, password reset

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
소셜 로그인 구현 및  비밀번호 재설정 endpoint 구현

## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.

2021-02-02 08:53 UTC, jamessoun93 requested changes

2021-02-02 08:53 UTC, jamessoun93 commented on users/views.py
> +            if password['resetPassword'] != password['resetRePassword']:
처음 입력하는 비밀번호와 재입력한 비밀번호를 비교하는 건 프론트에서 한 뒤 최종적으로 해당 조건을 pass 한 뒤 넘어오는 비밀번호만 대조하면 불필요한 코드를 없앨 수 있을뿐만 아니라 불필요한 호출도 없앨 수 있겠죠?

2021-02-02 10:03 UTC, FreshTuna commented on users/views.py
> +            if password['resetPassword'] != password['resetRePassword']:
넵! 그럴거 같네요... 프런트와 상의해서 변경하도록 하겠습니다!

2021-02-03 01:31 UTC, jamessoun93 approved these changes
LGTM

2021-02-03 01:31 UTC, merged